name: Expressions And Contexts
on: [push,pull_request]
run-name: "Expressions and Contexts by @${{github.actor}},events:${{github.event_name}}"
jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name=='issues' || github.event_name == 'pull_request' 
    steps:
      - name: expressions
        id : expressions
        run: |
            echo ${{1}}
            echo ${{'THis is a string'}}
            echo ${{null}}
            echo ${{true}}
            echo ${{2>1}}
            echo ${{'string'== 'String'}}
            echo ${{true && false}}
            echo ${{true || false}}
      - name: contexts
        run: |
             echo '${{toJson(github)}}'
             echo '${{toJson(job)}}'
             echo '${{toJson(secrets)}}'
             echo '${{toJson(steps)}}'
             echo '${{toJson(runner)}}'
             
 

