---
    name: manual-workflow
    on:
      workflow_dispatch:
        inputs:
          string:
            description: A String Input
            type: string
            required: true
            default: A default value
          
    jobs:
      log-info:
        runs-on: ubuntu-latest
        steps:
          - run: echo $GITHUB_REF
          - run: |
              echo "String: ${{inputs.string}}"
              echo "Numbers: ${{inputs.number}}"
              echo "Option: ${{inputs.option}}"
              echo "Boolean: ${{inputs.boolean}}"
              echo "Envt: ${{inputs.environment}}"
    