name: Repo-events
on: 
    push:
     # branches-ignore: 
     #   - dev
     #   - qa
     #   - uat
    # tags: 
    #  - v1.*
    #  - "!v1.1.1" #ignore specific version 
     paths:
      - "**.js"



    pull_request:
        types: [opened,assigned,reopened]
    issues:
        types: [opened]
jobs:
  checkout-labs:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo $GITHUB_SHA
         echo $GITHUB_REF
      - uses: actions/checkout@v3   
