name: Stale Issues & OR
on:
    schedule:
        - cron: "0 14 * * *"
        - cron: "0/5 * * * *"
jobs:
    Stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v9
              with:
               stale-issue-message: 'Message to comment on stale issues. If none provided, will not mark issues stale'
               stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
