name: working dirctory and shells
on: [push]
jobs:
    display-working-directory:
        runs-on: ubuntu-latest
        steps:
            - name: display the working directory and the list
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-working-directory-windows:
        runs-on: windows-latest
        steps:
            - name: display 
              run: |
                 Get-Location
                 dir
                 echo $GITHUB_SHA
                 echo $GITHUB_REPOSITORY
                 echo $GITHUB_WORKSPACE

