name: shells in Action
on: [push]
defaults:
    run:
      shell: bash
jobs:
    set-shell-at-Job-level:
     runs-on: ubuntu-latest
     defaults:
        run:
            shell: bash
        steps:
         - name: echo a string
          run: echo "Hello world"
