name: Status check function
'on':
  - push
  - pull_request
jobs:
   job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: sleep 20
      - name: step 2
        id : step-2
        run: exit 1
      - name: Runs on failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Runs only if step 2 on failure'
      - name: Runs on success
        if: success()
        run: echo 'Runs on success'
      - name: Runs on Always in the project
        if: always()
        run: echo 'Runs on always' 
      - name: Runs on Cancelled
        if: cancelled()
        run: echo 'Runs on cancelled'
   jobs-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job-2'        


         

   
  